name: harness-webapp-demo
replicas: 1
image: <+artifact.image>
dockercfg: <+artifact.imagePullSecret>

createNamespace: true
namespace: <+infra.namespace>
serviceType: ClusterIP
servicePort: 8000
serviceTargetPort: 8000
env:
 secrets:
    key2: value2