apiVersion: v1
kind: Service
metadata:
  name: nodeport-{{.Values.name}}
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    protocol: TCP
  selector:
    app: {{.Values.name}}